interface tweetfetcher {
    variant request {
        send(send-request),
        /// history of chat with given node
        history(string),
    }

    variant response {
        send,
        history(list<chat-message>),
    }

    record send-request {
        target: string,
        message: string,
    }

    record chat-message {
        author: string,
        content: string,
    }
}

world tweetfetcher-template-dot-os-v0 {
    import tweetfetcher;
    include process-v0;
}
